[build]
  base = "/"
  command = "npm run netlify-build"
  publish = "build"

# Handle SPA routing by redirecting all paths to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
# Set proper headers for security and caching
[[headers]]
  for = "/*"
    [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"